name: documon
description: "App para revisar la documentacion de los pokemones."
publish_to: 'JoanV'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  audioplayers: ^6.5.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/image/Icon_docu.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/audios/
    - assets/image/

  fonts: 
    - family: BespokeSlab
      fonts:
        - asset: assets/fonts/BespokeSlab-Regular.otf
        - asset: assets/fonts/BespokeSlab-Bold.otf
        - asset: assets/fonts/BespokeSlab-Medium.otf
        - asset: assets/fonts/BespokeSlab-MediumItalic.otf
